apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    name: demo
  namespace: demo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    name: demo
