kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    name: demo
  name: mongo-storage
  namespace: demo
spec:
  storageClassName: vmc-workload-storage-policy-cluster-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
